version: '3.8'

services:
  api:
    build: ./build/api
    container_name: ${API_CONTAINER_NAME}
    volumes:
      - ./api:/go/src/app
    ports:
      - ${API_PORT}:8080
    tty: true
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: ${DB_HOST}
    environment:
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGDATABASE=${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./build/db/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432

volumes:
  postgres-data:
