services:
  nginx:
    build: ./nginx
    container_name: ${NGINX_CONTAINER_NAME}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - api

  frontend:
    build: ./frontend
    container_name: ${FRONTEND_CONTAINER_NAME}
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports:
      - ${FRONTEND_PORT}:3000
    # command: npm run dev
    tty: true
    depends_on:
      - api

  api:
    build: ./api
    container_name: ${API_CONTAINER_NAME}
    hostname: ${API_CONTAINER_NAME}
    volumes:
      - ./api/app:/go/src/app
    ports:
      - ${API_PORT}:8080
    # command: go run cmd/app/main.go -m test
    tty: true
    env_file:
      - .env
    depends_on:
      - db
      - db-test
      - redis

  db:
    image: postgres:alpine
    container_name: ${DB_HOST}
    hostname: ${DB_HOST}
    environment:
      # By setting these variables, specified user will be created with superuser power and a database with specified name.
      # So there is no need to create user and database in init.sql
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  db-test:
    image: postgres:alpine
    container_name: ${DB_TEST_HOST}
    hostname: ${DB_TEST_HOST}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_TEST_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  node_modules:
  postgres-data:
