// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/tweet"
	"api/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Tweet is the model entity for the Tweet schema.
type Tweet struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID *uuid.UUID `json:"parent_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TweetQuery when eager-loading is set.
	Edges        TweetEdges `json:"edges"`
	user_posts   *int
	selectValues sql.SelectValues
}

// TweetEdges holds the relations/edges for other nodes in the graph.
type TweetEdges struct {
	// PostedBy holds the value of the posted_by edge.
	PostedBy *User `json:"posted_by,omitempty"`
	// Child holds the value of the child edge.
	Child []*Tweet `json:"child,omitempty"`
	// Parent holds the value of the parent edge.
	Parent []*Tweet `json:"parent,omitempty"`
	// Has holds the value of the has edge.
	Has []*Like `json:"has,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// PostedByOrErr returns the PostedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TweetEdges) PostedByOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.PostedBy == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.PostedBy, nil
	}
	return nil, &NotLoadedError{edge: "posted_by"}
}

// ChildOrErr returns the Child value or an error if the edge
// was not loaded in eager-loading.
func (e TweetEdges) ChildOrErr() ([]*Tweet, error) {
	if e.loadedTypes[1] {
		return e.Child, nil
	}
	return nil, &NotLoadedError{edge: "child"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading.
func (e TweetEdges) ParentOrErr() ([]*Tweet, error) {
	if e.loadedTypes[2] {
		return e.Parent, nil
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// HasOrErr returns the Has value or an error if the edge
// was not loaded in eager-loading.
func (e TweetEdges) HasOrErr() ([]*Like, error) {
	if e.loadedTypes[3] {
		return e.Has, nil
	}
	return nil, &NotLoadedError{edge: "has"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tweet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tweet.FieldParentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case tweet.FieldID:
			values[i] = new(sql.NullInt64)
		case tweet.FieldText:
			values[i] = new(sql.NullString)
		case tweet.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case tweet.FieldUserID:
			values[i] = new(uuid.UUID)
		case tweet.ForeignKeys[0]: // user_posts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tweet fields.
func (t *Tweet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tweet.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case tweet.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				t.Text = value.String
			}
		case tweet.FieldParentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				t.ParentID = new(uuid.UUID)
				*t.ParentID = *value.S.(*uuid.UUID)
			}
		case tweet.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				t.UserID = *value
			}
		case tweet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				t.CreatedAt = value.Time
			}
		case tweet.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_posts", value)
			} else if value.Valid {
				t.user_posts = new(int)
				*t.user_posts = int(value.Int64)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tweet.
// This includes values selected through modifiers, order, etc.
func (t *Tweet) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryPostedBy queries the "posted_by" edge of the Tweet entity.
func (t *Tweet) QueryPostedBy() *UserQuery {
	return NewTweetClient(t.config).QueryPostedBy(t)
}

// QueryChild queries the "child" edge of the Tweet entity.
func (t *Tweet) QueryChild() *TweetQuery {
	return NewTweetClient(t.config).QueryChild(t)
}

// QueryParent queries the "parent" edge of the Tweet entity.
func (t *Tweet) QueryParent() *TweetQuery {
	return NewTweetClient(t.config).QueryParent(t)
}

// QueryHas queries the "has" edge of the Tweet entity.
func (t *Tweet) QueryHas() *LikeQuery {
	return NewTweetClient(t.config).QueryHas(t)
}

// Update returns a builder for updating this Tweet.
// Note that you need to call Tweet.Unwrap() before calling this method if this Tweet
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Tweet) Update() *TweetUpdateOne {
	return NewTweetClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Tweet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Tweet) Unwrap() *Tweet {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tweet is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Tweet) String() string {
	var builder strings.Builder
	builder.WriteString("Tweet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("text=")
	builder.WriteString(t.Text)
	builder.WriteString(", ")
	if v := t.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", t.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(t.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tweets is a parsable slice of Tweet.
type Tweets []*Tweet
