// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package app

type RefreshTokenResponse struct {
	AccessToken string `json:"accessToken"`
}

type SigninResponse struct {
	UserID       int    `json:"userId"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}
