name: Go CI

on:
  push:
    paths:
      - api/app/**
      - .github/workflows/goCI.yml
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Build
        working-directory: ./api/app
        run: go build -v

      - name: Test
        working-directory: ./api/app
        run: go test -v ./...
