name: Go CI

on:
  push:
    paths:
      - api/app/**
      - .github/workflows/goCI.yml
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Go mod tidy
        working-directory: ./api/app
        run: go mod tidy

      - name: Build
        working-directory: ./api/app
        run: go build -v

      - name: Test
        working-directory: ./api/app
        run: go test -v ./...
